# Generated by Django 2.1 on 2018-08-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cacheapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name_plural': '蛋糕'},
        ),
    ]
